<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260411204653 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE apartment_apartment_group (apartment_id INT NOT NULL, apartment_group_id INT NOT NULL, PRIMARY KEY (apartment_id, apartment_group_id))');
        $this->addSql('CREATE INDEX IDX_1D56EA73176DFE85 ON apartment_apartment_group (apartment_id)');
        $this->addSql('CREATE INDEX IDX_1D56EA73F3B58597 ON apartment_apartment_group (apartment_group_id)');
        $this->addSql('CREATE TABLE apartment_group (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2A071708727ACA70 ON apartment_group (parent_id)');
        $this->addSql('CREATE TABLE user_apartment_group (user_id INT NOT NULL, apartment_group_id INT NOT NULL, PRIMARY KEY (user_id, apartment_group_id))');
        $this->addSql('CREATE INDEX IDX_38DB7B87A76ED395 ON user_apartment_group (user_id)');
        $this->addSql('CREATE INDEX IDX_38DB7B87F3B58597 ON user_apartment_group (apartment_group_id)');
        $this->addSql('CREATE TABLE vapi_assistant_config (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, prompt TEXT NOT NULL, first_message TEXT NOT NULL, time_limit INT NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE apartment_apartment_group ADD CONSTRAINT FK_1D56EA73176DFE85 FOREIGN KEY (apartment_id) REFERENCES apartment (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE apartment_apartment_group ADD CONSTRAINT FK_1D56EA73F3B58597 FOREIGN KEY (apartment_group_id) REFERENCES apartment_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE apartment_group ADD CONSTRAINT FK_2A071708727ACA70 FOREIGN KEY (parent_id) REFERENCES apartment_group (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_apartment_group ADD CONSTRAINT FK_38DB7B87A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_apartment_group ADD CONSTRAINT FK_38DB7B87F3B58597 FOREIGN KEY (apartment_group_id) REFERENCES apartment_group (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE apartment_apartment_group DROP CONSTRAINT FK_1D56EA73176DFE85');
        $this->addSql('ALTER TABLE apartment_apartment_group DROP CONSTRAINT FK_1D56EA73F3B58597');
        $this->addSql('ALTER TABLE apartment_group DROP CONSTRAINT FK_2A071708727ACA70');
        $this->addSql('ALTER TABLE user_apartment_group DROP CONSTRAINT FK_38DB7B87A76ED395');
        $this->addSql('ALTER TABLE user_apartment_group DROP CONSTRAINT FK_38DB7B87F3B58597');
        $this->addSql('DROP TABLE apartment_apartment_group');
        $this->addSql('DROP TABLE apartment_group');
        $this->addSql('DROP TABLE user_apartment_group');
        $this->addSql('DROP TABLE vapi_assistant_config');
    }
}
